- name: Put contour template
  template:
    src: contour.yml.j2
    dest: /tmp/contour.yml
    owner: root
    group: "0777"

- name: Setup contour
  command: kubectl apply -f /tmp/contour.yml
  args:
    chdir: $HOME
    creates: contour-apply.log
