- name: Create dir /etc/apt/keyrings if not exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Install needs packages to https and gpc no apt
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Download Kubernetes v1.33
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /tmp/kubernetes-release.key

- name: Convert GPG key to keyring format and save to /etc/apt/keyrings
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Adjust keyring file permissions to read-only
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

- name: Create Kubernetes v1.33 repository file
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    mode: '0644'

- name: Update APT cache
  apt:
    update_cache: yes
