- name: Ensure snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snap core is installed and refreshed
  ansible.builtin.shell: snap install core && snap refresh core
  args:
    creates: /snap/bin/core

- name: Install certbot using snap
  ansible.builtin.command: snap install --classic certbot
  args:
    creates: /snap/bin/certbot

- name: Create symlink for certbot
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: yes

- name: check if certificate exists
  stat:
   path: /etc/letsencrypt/live/{{cert_domain_name}}//cert.pem
  register: cert_exists

- name: check if certificate exists
  wait_for:
     port: 80
     delay: 0
     timeout: 5
     state: stopped
     msg: "Port 80 already allocate"
  register: service_status
  ignore_errors: yes

- name: debug service status
  ansible.builtin.debug:
    var: service_status 

- name: debug cert status
  ansible.builtin.debug:
    var: cert_exists

- name: Generate SSL certificate
  ansible.builtin.command: certbot certonly --standalone -d {{ cert_domain_name }} --email {{ cert_admin_email }} --agree-tos --non-interactive
  when:
    - cert_exists.stat.exists == false
    - service_status.state == "stopped"